version: '3'

volumes:
    cowsdb_data: {}

services:

  cowsdb-server:
    image: ghcr.io/cowsdb/cowsdb:latest
    container_name: cowsdb-server
    restart: unless-stopped
    expose:
      - 8123
    volumes:
      - cowsdb_data:/app/.chdb_data
    environment:
      - PORT=8123
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 500M

  qryn:
    image: qxip/qryn:latest
    container_name: qryn-cowsdb
    restart: unless-stopped
    expose:
      - 3100
    ports:
      - "3100:3100"
    environment:
      - CLICKHOUSE_SERVER=cowsdb-server
      - CLICKHOUSE_AUTH="qryn:demo"
      - CLICKHOUSE_PORT=8123
      - NODE_OPTIONS="--max-old-space-size=4096"
    depends_on:
       - cowsdb-server
